import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

const routePlanPath = fileURLToPath(
  new URL("../../front-door/route-groups.json", import.meta.url),
);
const outputPath = fileURLToPath(new URL("../src/routes.generated.mjs", import.meta.url));
const checkOnly = process.argv.includes("--check");

const routePlan = JSON.parse(await readFile(routePlanPath, "utf8"));
const staticGroup = routePlan.route_groups.find((group) => group.id === "public_static_site");
if (!staticGroup) {
  throw new Error("public_static_site route group is missing");
}

const staticContentTypes = Object.fromEntries(
  staticGroup.paths.map(({ kind, value }) => {
    if (kind !== "exact") {
      throw new Error(`Static route is not exact: ${value}`);
    }
    return [value, legacyContentType(value === "/" ? "/index.html" : value)];
  }),
);

const apiPaths = routePlan.route_groups
  .filter((group) => group.future_backend === "cloud_run_api")
  .flatMap((group) => group.paths);
const apiExactPaths = apiPaths
  .filter(({ kind }) => kind === "exact")
  .map(({ value }) => value);
const apiPrefixPaths = apiPaths
  .filter(({ kind }) => kind === "prefix")
  .map(({ value }) => value);

if (Object.keys(staticContentTypes).length !== 79) {
  throw new Error("Static route count changed from 79");
}
if (apiExactPaths.length !== 17 || apiPrefixPaths.length !== 2) {
  throw new Error("Cloud Run route count changed from 17 exact and 2 prefix routes");
}

const output = `// Generated by scripts/generate-routes.mjs. Do not edit directly.\n\n` +
  `export const STATIC_CONTENT_TYPES = Object.freeze(${json(staticContentTypes)});\n\n` +
  `export const API_EXACT_PATHS = Object.freeze(${json(apiExactPaths)});\n\n` +
  `export const API_PREFIX_PATHS = Object.freeze(${json(apiPrefixPaths)});\n`;

if (checkOnly) {
  const current = await readFile(outputPath, "utf8");
  if (current !== output) {
    throw new Error("src/routes.generated.mjs is stale; run npm run generate:routes");
  }
} else {
  await writeFile(outputPath, output);
}

function legacyContentType(path) {
  const suffix = path.includes(".") ? path.slice(path.lastIndexOf(".")).toLowerCase() : "";
  return {
    ".html": "text/html",
    ".htm": "text/html",
    ".css": "text/css",
    ".js": "application/javascript",
    ".json": "application/json",
    ".jpeg": "image/jpeg",
    ".jpg": "image/jpeg",
    ".png": "image/png",
    ".svg": "image/svg+xml",
  }[suffix] ?? "text/plain";
}

function json(value) {
  return JSON.stringify(value, null, 2);
}
